#!/bin/sh /etc/rc.common
# description: Cosmos Cloud service
# processname: /opt/cosmos/start.sh

START=99
STOP=01
USE_PROCD=1
#PROCD_DEBUG=1

start_service() {
        procd_open_instance
        procd_set_param command /bin/sh "/opt/cosmos/start.sh"
        procd_append_param command daemon
        procd_set_param pidfile /var/run/CosmosCloud.pid
        procd_set_param term_timeout 60
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_set_param respawn 150 10 10
        procd_close_instance
}